### PR TITLE
Make urls.py ready for django > 1.4

### PR DESCRIPTION
**Pull request by salvadorven**

### CODE REVIEW

**Comment by Kami** [comment]
@jorgebastida any updates on this one?

It would be great if you could merge it. Django 1.6 removed support for deprecated `django.conf.urls.defaults` (https://docs.djangoproject.com/en/dev/internals/deprecation/).

Thanks

**Comment by Dan-stahr** [comment]
+1 for this one, Django 1.6 is now oficially live in PyPI.

**Comment by bufke** [comment]
This would be good to fix. I can offer help maintaining if you don't have time to review these pull requests.

**Comment by icalvete** [comment]
+1

**Comment by Kami** [comment]
@jorgebastida If you don't have time to maintain the project, I'm also more than happy to help with maintaining it (I have multiple active projects which use dajaxice).

**Comment by jorgebastida** [comment]
django-dajaxice 0.6 fixes this issue. Thanks!

**Pull request closed without merging**
