### PR TITLE
Adds support for Django 1.6 w/o breaking older versions

### PR DESCRIPTION
**Pull request by sbywater**

### CODE REVIEW

**Comment by sbywater** [comment]
This Travis CI build (and several others) are breaking through no fault of this commit.

Travis CI reports:

File "/home/travis/virtualenv/python3.2/bin/app-test-runner", line 2, in <module>
import app_test_runner
File "/home/travis/virtualenv/python3.2/lib/python3.2/site-packages/app_test_runner.py", line 40
print "You did not provide an app path."

... with a syntax on the last line because python 3.2 has a different syntax for print. Since django-app-test-runner hasn't been updated in four years, that is no surprise.

**Comment by difanz** [comment]
The tests should be fixed as well.

https://github.com/ifanrx/django-dajaxice/commit/596a2c4bce5423f7047b05d2040a1f9c3c710cab

I dropped Django<1.0 support there. Presumably nobody's using that. And shouldn't be using that.

**Comment by maoaiz** [comment]
I'm working with django 1.6, the last realease (0.5.5) only has support for django 1.5

What do I need to do? I don't want to modified the library, I'm using it from pypi because I want an stable version. can you help me about what I need to do?

**Comment by difanz** [comment]
@MaoAiz seems this project was abandoned. Use django-dajaxice-ng

**Comment by maoaiz** [comment]
thanks @cheungtifan

**Comment by jorgebastida** [comment]
django-dajaxice 0.6 fixes this issue. Thanks!

**Pull request closed without merging**
