### PR TITLE
Option to generate static JS directly into a static/ directory (for use with staticpages)

### PR DESCRIPTION
**Pull request by fish2000**
Added --static=STATIC_FILENAME option to generate_static_dajaxice, which saves the static js output in a static/ directory (per Django 1.3's staticpages app) before calling 'manage.py collect static'.

Omitting the option prints the js output as usual.

### CODE REVIEW

**Comment by jorgebastida** [comment]
Hi fish2000,

First of all thank you very much for your pull request.

This is a very good idea, but I've some doubts about how appropriate is the place where the command generates the file.

I think that saving the file inside the module dir isn't a good idea. If you aren't using a unique virtualenv for every project and you store (i.e.) project-a dajaxice.core.js file insde /dajaxice/static/{static_name} and in projectc-b you call the collectstatic command before calling this command the project-b will recollect the wrong file.

What do you think about creating a new Finder [1] ? (ie. DajaxiceFinder)

We will reduce the problem to simply call the collectstatic command and we will never forget call the generate_static_dajaxice command before.

[1] https://docs.djangoproject.com/en/dev/ref/contrib/staticfiles/#staticfiles-finders

One more time, thank you very much.

Cheers!

**Comment by divadrei** [comment]
The finder should be a good solution but : "Static file finders are currently considered a private interface, and this interface is thus undocumented." the only way to do this is writing a storage and creating a finder with BaseStorageFinder inheritance.

**Comment by divadrei** [comment]
Static file finder implementation : https://github.com/oxys-net/django-dajaxice

Just add 'dajaxice.finder.DajaxiceFinder' to your STATICFILES_FINDERS, collect static will create the file and you can use CachedStaticFilesStorage.

**Comment by fish2000** [comment]
@oxys nice -- merged yr changes to try them out. salud.

**Comment by divadrei** [comment]
PS : no js optimisation, I don't think dajax is the right place to do this, with the finder you can use django-pipeline for example :

PIPELINE_JS = {
    'lazy': {
        'source_filenames': (
            'js/libs/jquery.dajax.core.js',
            'js/....js',
            'dajaxice/dajaxice.core.js',
        ),
        'output_filename': 'c/lazy.js',
    },

**Comment by jorgebastida** [comment]
I've rewrite completely django-dajaxice for the upcoming 0.5 version (currently on the development branch). Dajaxice now use all the staticfiles available features.

**Comment by divadrei** [comment]
VirtualStorage is a cleaner idea, when do you plan to release this version ?

**Comment by jorgebastida** [comment]
Everything is ready, so... soon (1week or less)

El 02/08/2012, a las 18:26, david
reply@reply.github.com
escribió:

**Comment by jorgebastida** [comment]
I've release django-dajaxice 0.5 http://pypi.python.org/pypi/django-dajaxice

**Pull request closed without merging**
